import { ProfileData, ProjectData, SkillData, CertificationData, TimelineData } from '@/types';

export const INITIAL_PROFILE: ProfileData = {
  id: 'default',
  name: 'Soundkish',
  headline: 'Securing Systems. Building Trust.',
  taglines: [
    'Cybersecurity Enthusiast',
    'AI Developer',
    'Full-Stack Developer',
    'Software Engineer',
  ],
  bio: "I'm Soundkish, a CSE student passionate about Cybersecurity, AI, and building secure, resilient digital solutions for a safer tomorrow.",
  resumeUrl: 'https://drive.google.com',
  socials: {
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'mailto:contact@soundkish.dev',
  },
  stats: {
    yearsLearning: '2+',
    projects: '15+',
    certifications: '10+',
    curiosity: '∞',
  },
  aboutModules: {
    showEducation: true,
    showFocus: true,
    showRoadmap: true,
    showSpecializations: true,
    showStats: true,
  },
  academicDegree: {
    degree: 'B.E. Computer Science & Engineering',
    college: 'SRM Valliammai Engineering College',
    year: '2024 – 2028',
    status: 'Active',
  },
  focusChips: [
    '✓ Cybersecurity',
    '✓ AI & Neural Nets',
    '✓ Backend Systems',
    '✓ Cloud Infrastructure',
    '✓ DevOps & Containers',
    '✓ Network Security',
  ],
  careerRoadmap: [
    { year: '2024', title: 'Started CSE Engineering', description: 'Foundation in computer science & security principles', iconName: 'GraduationCap', colorToken: 'emerald' },
    { year: '2025', title: 'Full Stack & Security Projects', description: 'Building web systems and pentesting labs', iconName: 'Code2', colorToken: 'cyan' },
    { year: '2026', title: 'AI + Cyber Threat Detection', description: 'Advanced machine learning for network intrusion', iconName: 'Cpu', colorToken: 'amber' },
    { year: 'Goal', title: 'Security Software Engineer', description: 'Production engineering and defense-in-depth', iconName: 'ShieldCheck', colorToken: 'rose' },
  ],
  statsCards: [
    { id: '1', value: '15+', label: 'Projects Built', colorToken: 'emerald', iconName: 'Rocket' },
    { id: '2', value: '10+', label: 'Certifications', colorToken: 'cyan', iconName: 'Award' },
    { id: '3', value: '2+', label: 'Years Learning', colorToken: 'emerald', iconName: 'Flame' },
    { id: '4', value: '∞', label: 'Curiosity', colorToken: 'amber', iconName: 'Sparkles' },
  ],
  specializationCards: [
    { id: '1', title: 'Cybersecurity', description: 'Application Security, Threat Detection & Vulnerability Analysis', iconName: 'ShieldCheck', colorToken: 'emerald' },
    { id: '2', title: 'AI Systems', description: 'Neural Networks, Computer Vision & Constraint Algorithms', iconName: 'Cpu', colorToken: 'cyan' },
    { id: '3', title: 'Cloud Infra', description: 'Scalable Microservices, Docker Containers & CI/CD Pipelines', iconName: 'Globe', colorToken: 'amber' },
    { id: '4', title: 'Networking', description: 'TCP/IP Architecture, Packet Analysis & Firewall Systems', iconName: 'Compass', colorToken: 'rose' },
    { id: '5', title: 'Backend Systems', description: 'FastAPI, Node.js, High-Throughput REST APIs & JWT Security', iconName: 'Code2', colorToken: 'purple' },
    { id: '6', title: 'Linux Kernel', description: 'Bash Scripting, System Administration & Access Controls', iconName: 'Terminal', colorToken: 'emerald' },
  ],
};

export const INITIAL_SKILLS: SkillData[] = [
  { id: '1', name: 'Python', category: 'Languages', icon: 'python', order: 1 },
  { id: '2', name: 'C / C++', category: 'Languages', icon: 'c', order: 2 },
  { id: '3', name: 'JavaScript / TS', category: 'Languages', icon: 'javascript', order: 3 },
  { id: '4', name: 'Linux', category: 'Security Tools', icon: 'linux', order: 4 },
  { id: '5', name: 'MySQL', category: 'Infra/DevOps', icon: 'mysql', order: 5 },
  { id: '6', name: 'Burp Suite', category: 'Security Tools', icon: 'burpsuite', order: 6 },
  { id: '7', name: 'Wireshark', category: 'Security Tools', icon: 'wireshark', order: 7 },
  { id: '8', name: 'Nmap', category: 'Security Tools', icon: 'nmap', order: 8 },
  { id: '9', name: 'Git', category: 'Infra/DevOps', icon: 'git', order: 9 },
  { id: '10', name: 'Docker', category: 'Infra/DevOps', icon: 'docker', order: 10 },
  { id: '11', name: 'FastAPI', category: 'Languages', icon: 'fastapi', order: 11 },
  { id: '12', name: 'OWASP Security', category: 'Security Tools', icon: 'owasp', order: 12 },
];

export const INITIAL_PROJECTS: ProjectData[] = [
  {
    id: '1',
    title: 'AI Timetable Generator',
    description: 'AI + rule-based system to generate optimized college timetables.',
    longDescription: 'An automated scheduling algorithm leveraging constraint satisfaction and genetic algorithms to solve complex university timetable conflicts with custom faculty, room, and student load constraints.',
    image: '/images/project-timetable.svg',
    tags: ['Python', 'FastAPI', 'AI'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    featured: true,
    order: 1,
    published: true,
  },
  {
    id: '2',
    title: 'Smart Campus ERP',
    description: 'Full-featured ERP for college management system with role-based access control.',
    longDescription: 'Comprehensive educational resource planning tool with fine-grained RBAC permission matrix, attendance tracking, secure grading portal, and dynamic audit logs.',
    image: '/images/project-erp.svg',
    tags: ['FastAPI', 'SQL', 'JWT'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    featured: true,
    order: 2,
    published: true,
  },
  {
    id: '3',
    title: 'Magizhvapam E-Commerce',
    description: 'E-commerce platform with secure payment integrations and admin analytics panel.',
    longDescription: 'Modern multi-vendor e-commerce engine with encrypted user sessions, PCI-compliant payment gateway flow, real-time inventory tracking, and sales reporting dashboard.',
    image: '/images/project-ecommerce.svg',
    tags: ['MongoDB', 'Express', 'React'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    featured: true,
    order: 3,
    published: true,
  },
  {
    id: '4',
    title: 'MangoMate (AI Ripeness)',
    description: 'AI-powered ripeness detection using convolutional neural networks and computer vision.',
    longDescription: 'Edge-deployable computer vision pipeline analyzing produce spectral color profiles and surface textures to classify fruit maturity levels with high accuracy.',
    image: '/images/project-mangomate.svg',
    tags: ['Python', 'CNN', 'OpenCV'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    featured: true,
    order: 4,
    published: true,
  },
];

export const INITIAL_CERTIFICATIONS: CertificationData[] = [
  {
    id: '1',
    title: 'Certified Ethical Hacker (CEH)',
    issuer: 'EC-Council',
    issueDate: '2025',
    credentialUrl: 'https://eccouncil.org',
    logoUrl: '/images/cert-ceh.svg',
    order: 1,
  },
  {
    id: '2',
    title: 'CompTIA Security+',
    issuer: 'CompTIA',
    issueDate: '2024',
    credentialUrl: 'https://comptia.org',
    logoUrl: '/images/cert-comptia.svg',
    order: 2,
  },
  {
    id: '3',
    title: 'AWS Certified Security - Specialty',
    issuer: 'Amazon Web Services',
    issueDate: '2025',
    credentialUrl: 'https://aws.amazon.com',
    logoUrl: '/images/cert-aws.svg',
    order: 3,
  },
  {
    id: '4',
    title: 'Google Cybersecurity Professional',
    issuer: 'Google',
    issueDate: '2024',
    credentialUrl: 'https://coursera.org',
    logoUrl: '/images/cert-google.svg',
    order: 4,
  },
];

export const INITIAL_TIMELINE: TimelineData[] = [
  {
    id: '1',
    year: '2022',
    title: 'Computer Science Foundations',
    subtitle: 'High School & Fundamentals',
    description: 'Explored programming basics in C and Python, mastering data structures, algorithms, and networking protocols.',
    category: 'Education',
    order: 1,
  },
  {
    id: '2',
    year: '2023',
    title: 'Entered CSE Degree & Cybersecurity Deep-Dive',
    subtitle: 'University Admission',
    description: 'Began B.Tech CSE degree. Focused on Linux administration, network packet inspection with Wireshark, and OWASP Top 10 vulnerabilities.',
    category: 'Education',
    order: 2,
  },
  {
    id: '3',
    year: '2024',
    title: 'Full-Stack Development & AI Projects',
    subtitle: 'Major System Builds',
    description: 'Engineered the AI Timetable Generator and Smart Campus ERP system using FastAPI, Next.js, and SQL databases.',
    category: 'Project',
    order: 3,
  },
  {
    id: '4',
    year: '2025',
    title: 'Penetration Testing & Security Certification',
    subtitle: 'CEH & AWS Security Specialist',
    description: 'Completed hands-on vulnerability assessment labs, CTF competitions, and acquired industry-standard security credentials.',
    category: 'Security',
    order: 4,
  },
  {
    id: '5',
    year: '2026',
    title: 'Advanced AI + Cyber Systems Architect',
    subtitle: 'Current Milestone',
    description: 'Designing autonomous vulnerability scanners, AI threat detection pipelines, and high-performance secure web applications.',
    category: 'Milestone',
    order: 5,
  },
];
