/**
 * MAGIZHVAGAM V4 — Site Settings Schema
 * 
 * Singleton document (_id: "active") storing the complete theme configuration.
 * Contains 16 CSS variable groups, typography, layout tokens, and metadata.
 * 
 * MIGRATION NOTE: This schema is accessed via dbAdapter.js only.
 * For PostgreSQL migration, convert this to a JSONB column structure.
 */

const mongoose = require('mongoose');

// ─── Default Theme Values: Deep Velvet Night ─────────────────────────────────

const DEEP_VELVET_DEFAULTS = {
  hdr: {
    bg: 'rgba(13,10,20,0.8)',
    border: '#3A2E4A',
    logo_text: '#C9913D',
    logo_size: '24',
    nav_link_color: '#F5F0E8',
    nav_link_hover: '#C9913D',
    nav_link_active: '#C9913D',
    nav_link_weight: '500',
    icon_color: '#F5F0E8',
    icon_hover: '#C9913D',
    sticky_bg: 'rgba(13,10,20,0.96)',
    sticky_shadow: '0 4px 32px rgba(0,0,0,0.4)',
    sticky_height: '64',
    height: '80',
    announcement_bg: '#C9913D',
    announcement_text: '#0D0A14'
  },
  nav: {
    dropdown_bg: '#1A1523',
    dropdown_border: '#3A2E4A',
    dropdown_shadow: '0 16px 48px rgba(0,0,0,0.5)',
    dropdown_item_color: '#F5F0E8',
    dropdown_item_hover_bg: 'rgba(201,145,61,0.1)',
    dropdown_item_hover_color: '#C9913D',
    mega_bg: '#1A1523',
    mega_accent: '#C9913D',
    mega_heading: '#F5F0E8',
    mega_link: '#B8B0C8',
    mega_promo_bg: 'rgba(201,145,61,0.08)',
    mobile_bg: '#0D0A14',
    mobile_item: '#F5F0E8'
  },
  hero: {
    bg_overlay: 'rgba(13,10,20,0.6)',
    overlay_opacity: '0.6',
    headline_color: '#F5F0E8',
    subheadline_color: '#B8B0C8',
    cta_primary_bg: '#C9913D',
    cta_primary_text: '#0D0A14',
    cta_primary_hover_bg: '#E0A84A',
    cta_secondary_border: 'rgba(201,145,61,0.5)',
    cta_secondary_text: '#C9913D',
    badge_bg: 'rgba(201,145,61,0.15)',
    badge_text: '#C9913D'
  },
  pc: {
    bg: '#1A1523',
    border: '#3A2E4A',
    border_radius: '14',
    shadow: '0 2px 12px rgba(0,0,0,0.3)',
    hover_shadow: '0 12px 40px rgba(0,0,0,0.5)',
    hover_translate_y: '6',
    image_bg: '#0D0A14',
    image_radius: '10',
    name_color: '#F5F0E8',
    name_weight: '600',
    category_color: '#7A6E8A',
    current_price_color: '#C9913D',
    original_price_color: '#5A4E6A',
    discount_badge_bg: '#C0392B',
    discount_badge_text: '#F5F0E8',
    flash_badge_bg: '#C9913D',
    flash_badge_text: '#0D0A14',
    rating_color: '#C9913D',
    rating_empty_color: '#3A2E4A',
    btn_bg: '#C9913D',
    btn_text: '#0D0A14',
    btn_hover_bg: '#E0A84A',
    wishlist_icon_color: '#5A4E6A',
    wishlist_icon_active: '#C0392B',
    stock_in_color: '#27AE60',
    stock_out_color: '#C0392B',
    stock_low_color: '#F39C12'
  },
  pdp: {
    gallery_border: '#3A2E4A',
    gallery_active_border: '#C9913D',
    gallery_thumb_radius: '8',
    title_color: '#F5F0E8',
    title_size: '32',
    price_color: '#C9913D',
    compare_price_color: '#5A4E6A',
    specs_heading_color: '#F5F0E8',
    specs_value_color: '#B8B0C8',
    tab_active_color: '#C9913D',
    tab_active_border: '#C9913D',
    tab_inactive_color: '#7A6E8A',
    review_star_color: '#C9913D',
    customization_panel_bg: '#1A1523',
    customization_panel_border: '#3A2E4A',
    '3d_viewer_bg': '#0D0A14',
    '3d_viewer_controls_color': '#C9913D'
  },
  btn: {
    primary_bg: '#C9913D',
    primary_text: '#0D0A14',
    primary_hover_bg: '#E0A84A',
    primary_radius: '10',
    primary_shadow: '0 4px 16px rgba(201,145,61,0.3)',
    secondary_bg: 'transparent',
    secondary_text: '#C9913D',
    secondary_border: '#C9913D',
    secondary_hover_bg: 'rgba(201,145,61,0.08)',
    ghost_bg: 'transparent',
    ghost_border: 'rgba(245,240,232,0.2)',
    ghost_text: '#F5F0E8',
    danger_bg: '#C0392B',
    danger_text: '#F5F0E8',
    disabled_bg: '#2A2035',
    disabled_text: '#5A4E6A',
    font_weight: '600',
    letter_spacing: '0.02em',
    transition: 'all 0.25s cubic-bezier(0.4,0,0.2,1)'
  },
  cart: {
    page_bg: '#0D0A14',
    item_card_bg: '#1A1523',
    item_card_border: '#3A2E4A',
    item_name_color: '#F5F0E8',
    item_price_color: '#C9913D',
    quantity_btn_bg: '#2A2035',
    quantity_btn_border: '#3A2E4A',
    quantity_input_bg: '#1A1523',
    coupon_input_bg: '#1A1523',
    coupon_input_border: '#3A2E4A',
    coupon_btn_bg: '#C9913D',
    coupon_success_color: '#27AE60',
    coupon_error_color: '#C0392B',
    warning_banner_bg: 'rgba(192,57,43,0.1)',
    warning_banner_text: '#E74C3C',
    warning_banner_border: 'rgba(192,57,43,0.3)',
    summary_card_bg: '#1A1523',
    summary_card_border: '#3A2E4A',
    total_label_color: '#B8B0C8',
    total_value_color: '#F5F0E8',
    whatsapp_btn_bg: '#1A6B3C',
    whatsapp_btn_text: '#F5F0E8',
    whatsapp_btn_hover_bg: '#217A46',
    checkout_btn_bg: '#C9913D',
    checkout_btn_text: '#0D0A14'
  },
  co: {
    page_bg: '#0D0A14',
    step_indicator_active: '#C9913D',
    step_indicator_complete: '#27AE60',
    step_indicator_pending: '#3A2E4A',
    step_line_color: '#3A2E4A',
    address_card_bg: '#1A1523',
    address_card_border: '#3A2E4A',
    address_card_selected_border: '#C9913D',
    address_card_selected_shadow: '0 0 0 2px rgba(201,145,61,0.3)',
    form_label_color: '#B8B0C8',
    form_input_bg: '#1A1523',
    form_input_border: '#3A2E4A',
    form_input_focus_border: '#C9913D',
    form_input_error_border: '#C0392B',
    payment_option_bg: '#1A1523',
    payment_option_border: '#3A2E4A',
    payment_active_bg: 'rgba(201,145,61,0.08)',
    order_summary_bg: '#1A1523',
    place_order_btn_bg: '#C9913D',
    place_order_btn_text: '#0D0A14'
  },
  ft: {
    bg: '#0A0810',
    border_top: '#3A2E4A',
    logo_text: '#C9913D',
    heading_color: '#F5F0E8',
    link_color: '#7A6E8A',
    link_hover_color: '#C9913D',
    divider_color: '#2A2035',
    copyright_bg: '#070509',
    copyright_text: '#5A4E6A',
    newsletter_input_bg: '#1A1523',
    newsletter_input_border: '#3A2E4A',
    newsletter_btn_bg: '#C9913D',
    newsletter_btn_text: '#0D0A14',
    social_icon_color: '#7A6E8A',
    social_icon_hover_color: '#C9913D',
    social_icon_bg: 'rgba(201,145,61,0.08)',
    social_icon_hover_bg: 'rgba(201,145,61,0.15)'
  },
  frm: {
    input_bg: '#1A1523',
    input_border: '#3A2E4A',
    input_border_radius: '8',
    input_focus_border: '#C9913D',
    input_focus_shadow: '0 0 0 3px rgba(201,145,61,0.2)',
    input_placeholder_color: '#4A3E5A',
    input_text_color: '#F5F0E8',
    input_error_border: '#C0392B',
    input_error_text: '#E74C3C',
    input_success_border: '#27AE60',
    input_success_text: '#2ECC71',
    label_color: '#B8B0C8',
    label_weight: '500',
    helper_text_color: '#7A6E8A',
    strength_weak: '#C0392B',
    strength_fair: '#F39C12',
    strength_strong: '#27AE60',
    strength_perfect: '#C9913D'
  },
  mod: {
    backdrop_color: 'rgba(7,5,9,0.85)',
    backdrop_blur: '8',
    modal_bg: '#1A1523',
    modal_border: '#3A2E4A',
    modal_radius: '20',
    modal_shadow: '0 32px 80px rgba(0,0,0,0.7)',
    modal_header_bg: 'rgba(201,145,61,0.05)',
    modal_header_border: '#3A2E4A',
    modal_title_color: '#F5F0E8',
    modal_close_color: '#7A6E8A',
    modal_close_hover_color: '#F5F0E8',
    drawer_bg: '#1A1523',
    drawer_shadow: '-8px 0 40px rgba(0,0,0,0.5)',
    toast_success_bg: 'rgba(39,174,96,0.15)',
    toast_error_bg: 'rgba(192,57,43,0.15)',
    toast_warning_bg: 'rgba(243,156,18,0.15)',
    toast_info_bg: 'rgba(201,145,61,0.15)',
    toast_text_color: '#F5F0E8'
  },
  bdg: {
    new_bg: 'rgba(201,145,61,0.15)',
    new_text: '#C9913D',
    sale_bg: 'rgba(192,57,43,0.15)',
    sale_text: '#E74C3C',
    flash_bg: '#C9913D',
    flash_text: '#0D0A14',
    trending_bg: 'rgba(39,174,96,0.15)',
    trending_text: '#2ECC71',
    out_of_stock_bg: 'rgba(90,78,106,0.3)',
    out_of_stock_text: '#7A6E8A',
    limited_bg: 'rgba(243,156,18,0.15)',
    limited_text: '#F39C12',
    featured_bg: 'rgba(201,145,61,0.2)',
    featured_text: '#C9913D',
    radius: '6',
    font_weight: '700',
    padding: '4px 10px'
  },
  cd: {
    container_bg: 'rgba(201,145,61,0.05)',
    container_border: 'rgba(201,145,61,0.15)',
    container_radius: '12',
    digit_bg: '#1A1523',
    digit_text: '#F5F0E8',
    digit_border: '#3A2E4A',
    digit_radius: '8',
    separator_color: '#C9913D',
    label_color: '#7A6E8A',
    expired_bg: 'rgba(192,57,43,0.1)',
    expired_text: '#E74C3C',
    flash_sale_accent: '#C9913D'
  },
  acc: {
    page_bg: '#0D0A14',
    tab_active_color: '#C9913D',
    tab_active_border: '#C9913D',
    tab_inactive_color: '#7A6E8A',
    order_card_bg: '#1A1523',
    order_card_border: '#3A2E4A',
    status_pending: '#F39C12',
    status_confirmed: '#3498DB',
    status_shipped: '#9B59B6',
    status_delivered: '#27AE60',
    status_cancelled: '#C0392B',
    address_card_bg: '#1A1523',
    address_card_border: '#3A2E4A',
    address_cap_warning_bg: 'rgba(243,156,18,0.1)',
    address_cap_warning_text: '#F39C12'
  },
  st: {
    empty_icon_color: '#3A2E4A',
    empty_heading_color: '#F5F0E8',
    empty_text_color: '#7A6E8A',
    empty_cta_bg: '#C9913D',
    error_icon_color: '#C0392B',
    error_heading_color: '#F5F0E8',
    error_text_color: '#B8B0C8',
    success_icon_color: '#27AE60',
    success_heading_color: '#F5F0E8',
    success_text_color: '#B8B0C8',
    loading_spinner_color: '#C9913D',
    skeleton_base_color: '#1A1523',
    skeleton_shimmer_color: '#2A2035'
  },
  adm: {
    sidebar_bg: '#0A0810',
    sidebar_border: '#2A2035',
    sidebar_link_color: '#7A6E8A',
    sidebar_link_hover_bg: 'rgba(201,145,61,0.08)',
    sidebar_link_active_bg: 'rgba(201,145,61,0.12)',
    sidebar_link_active_text: '#C9913D',
    topbar_bg: '#1A1523',
    topbar_border: '#2A2035',
    topbar_title_color: '#F5F0E8',
    stat_card_bg: '#1A1523',
    stat_card_border: '#2A2035',
    table_header_bg: 'rgba(201,145,61,0.05)',
    table_row_hover: 'rgba(201,145,61,0.04)',
    table_border: '#2A2035',
    action_btn_edit_color: '#3498DB',
    action_btn_delete_color: '#C0392B',
    toggle_active_bg: '#C9913D',
    toggle_inactive_bg: '#3A2E4A',
    settings_tab_active: '#C9913D'
  },
  glass: {
    enabled: true,
    blur: '12',
    bg_opacity: '0.12',
    border_opacity: '0.15',
    shadow_intensity: '1.0',
    border_radius: '16',
    brightness: '1.0',
    contrast: '1.0',
    hover_intensity: '1.1',
    header_enabled: true,
    product_card_enabled: true,
    modal_enabled: true,
    sidebar_enabled: true,
    footer_enabled: true,
    form_enabled: true,
    hero_enabled: true
  }
};

// ─── Schema Definition ──────────────────────────────────────────────────────

const SiteSettingsSchema = new mongoose.Schema({
  _id: { type: String, default: 'active' },
  version: { type: Number, default: 0 },
  updatedAt: { type: Date, default: Date.now },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, default: null },
  theme: {
    hdr: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.hdr }) },
    nav: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.nav }) },
    hero: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.hero }) },
    pc: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.pc }) },
    pdp: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.pdp }) },
    btn: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.btn }) },
    cart: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.cart }) },
    co: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.co }) },
    ft: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.ft }) },
    frm: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.frm }) },
    mod: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.mod }) },
    bdg: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.bdg }) },
    cd: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.cd }) },
    acc: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.acc }) },
    st: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.st }) },
    adm: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.adm }) },
    glass: { type: mongoose.Schema.Types.Mixed, default: () => ({ ...DEEP_VELVET_DEFAULTS.glass }) }
  },
  typography: {
    display:  { family: { type: String, default: 'Cormorant Garamond' }, weights: { type: [Number], default: [400, 600, 700] }, fallback: { type: String, default: 'Georgia, serif' } },
    heading:  { family: { type: String, default: 'Cormorant Garamond' }, weights: { type: [Number], default: [600, 700] }, fallback: { type: String, default: 'Georgia, serif' } },
    body:     { family: { type: String, default: 'DM Sans' }, weights: { type: [Number], default: [300, 400, 500, 600, 700] }, fallback: { type: String, default: 'system-ui, sans-serif' } },
    price:    { family: { type: String, default: 'JetBrains Mono' }, weights: { type: [Number], default: [400, 500, 700] }, fallback: { type: String, default: 'monospace' } },
    button:   { family: { type: String, default: 'DM Sans' }, weights: { type: [Number], default: [500, 600, 700] }, fallback: { type: String, default: 'system-ui, sans-serif' } },
    badge:    { family: { type: String, default: 'DM Sans' }, weights: { type: [Number], default: [600, 700] }, fallback: { type: String, default: 'system-ui, sans-serif' } },
    scaleMultiplier: { type: Number, min: 0.9, max: 1.15, default: 1 }
  },
  layout: {
    containerMaxWidth: { type: Number, min: 1024, max: 1600, default: 1280 },
    sectionPaddingY:   { type: Number, min: 24, max: 160, default: 80 },
    sectionPaddingX:   { type: Number, min: 16, max: 96, default: 24 },
    gridGap:           { type: Number, min: 8, max: 48, default: 24 },
    cardRadius:        { type: Number, min: 0, max: 32, default: 14 },
    btnRadius:         { type: Number, min: 0, max: 32, default: 10 },
    inputRadius:       { type: Number, min: 0, max: 24, default: 8 },
    borderWidth:       { type: Number, min: 0, max: 4, default: 1 },
    shadowStrength:    { type: Number, min: 0, max: 3, default: 1 },
    glassOpacity:      { type: Number, min: 0, max: 1, default: 0.06 },
    glassBlur:         { type: Number, min: 0, max: 24, default: 12 },
    animationSpeed:    { type: Number, min: 0.5, max: 2, default: 1 }
  },
  meta: {
    activePresetId: { type: String, default: null },
    storeName: { type: String, default: 'MAGIZHVAGAM' },
    storeTagline: { type: String, default: 'Place of Happiness' },
    seoTitle: { type: String, default: 'MAGIZHVAGAM | Premium Return Gifts & Customized Gift Store' },
    seoDescription: { type: String, default: 'Premium Return Gifts & Customized Gifts for Weddings, Birthdays, Baby Showers, Corporate events, and Festivals.' },
    contactEmail: { type: String, default: '' },
    contactPhone: { type: String, default: '' },
    contactAddress: { type: String, default: '' },
    socialLinks: {
      instagram: { type: String, default: '' },
      facebook: { type: String, default: '' },
      twitter: { type: String, default: '' },
      youtube: { type: String, default: '' },
      whatsapp: { type: String, default: '' }
    }
  },
  customCss: { type: String, default: '' }
}, { _id: false, timestamps: false, collection: 'site_settings_v4' });

// Export defaults for use in theme-loader fallback
SiteSettingsSchema.statics.DEEP_VELVET_DEFAULTS = DEEP_VELVET_DEFAULTS;

module.exports = mongoose.model('SiteSettingsV4', SiteSettingsSchema);
